// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/player_controller.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/player_controller.proto</summary>
  public static partial class PlayerControllerReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/player_controller.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerControllerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvcGxheWVyX2NvbnRyb2xs",
            "ZXIucHJvdG8SG2RlY2VudHJhbGFuZC5zZGsuY29tcG9uZW50cyJzChJQQlBs",
            "YXllckNvbnRyb2xsZXISDwoHZ3Jhdml0eRgBIAEoDRISCgpqdW1wX2ZvcmNl",
            "GAIgASgNEhYKDm1vdmVtZW50X3NwZWVkGAMgASgNEiAKGHJ1bm5pbmdfc3Bl",
            "ZWRfbXVsdGlwbGllchgEIAEoDUIUqgIRRENMLkVDU0NvbXBvbmVudHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBPlayerController), global::DCL.ECSComponents.PBPlayerController.Parser, new[]{ "Gravity", "JumpForce", "MovementSpeed", "RunningSpeedMultiplier" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// PlayerIdentityData is used to read the information about the avatar's
  /// identity. this component is written by the engine using the communications
  /// transports' data.
  /// </summary>
  public sealed partial class PBPlayerController : pb::IMessage<PBPlayerController>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBPlayerController> _parser = new pb::MessageParser<PBPlayerController>(() => new PBPlayerController());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBPlayerController> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.PlayerControllerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerController() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerController(PBPlayerController other) : this() {
      gravity_ = other.gravity_;
      jumpForce_ = other.jumpForce_;
      movementSpeed_ = other.movementSpeed_;
      runningSpeedMultiplier_ = other.runningSpeedMultiplier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerController Clone() {
      return new PBPlayerController(this);
    }

    /// <summary>Field number for the "gravity" field.</summary>
    public const int GravityFieldNumber = 1;
    private uint gravity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Gravity {
      get { return gravity_; }
      set {
        gravity_ = value;
      }
    }

    /// <summary>Field number for the "jump_force" field.</summary>
    public const int JumpForceFieldNumber = 2;
    private uint jumpForce_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JumpForce {
      get { return jumpForce_; }
      set {
        jumpForce_ = value;
      }
    }

    /// <summary>Field number for the "movement_speed" field.</summary>
    public const int MovementSpeedFieldNumber = 3;
    private uint movementSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MovementSpeed {
      get { return movementSpeed_; }
      set {
        movementSpeed_ = value;
      }
    }

    /// <summary>Field number for the "running_speed_multiplier" field.</summary>
    public const int RunningSpeedMultiplierFieldNumber = 4;
    private uint runningSpeedMultiplier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RunningSpeedMultiplier {
      get { return runningSpeedMultiplier_; }
      set {
        runningSpeedMultiplier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBPlayerController);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBPlayerController other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Gravity != other.Gravity) return false;
      if (JumpForce != other.JumpForce) return false;
      if (MovementSpeed != other.MovementSpeed) return false;
      if (RunningSpeedMultiplier != other.RunningSpeedMultiplier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Gravity != 0) hash ^= Gravity.GetHashCode();
      if (JumpForce != 0) hash ^= JumpForce.GetHashCode();
      if (MovementSpeed != 0) hash ^= MovementSpeed.GetHashCode();
      if (RunningSpeedMultiplier != 0) hash ^= RunningSpeedMultiplier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Gravity != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Gravity);
      }
      if (JumpForce != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JumpForce);
      }
      if (MovementSpeed != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MovementSpeed);
      }
      if (RunningSpeedMultiplier != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RunningSpeedMultiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Gravity != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Gravity);
      }
      if (JumpForce != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JumpForce);
      }
      if (MovementSpeed != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MovementSpeed);
      }
      if (RunningSpeedMultiplier != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RunningSpeedMultiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Gravity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Gravity);
      }
      if (JumpForce != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JumpForce);
      }
      if (MovementSpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MovementSpeed);
      }
      if (RunningSpeedMultiplier != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RunningSpeedMultiplier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBPlayerController other) {
      if (other == null) {
        return;
      }
      if (other.Gravity != 0) {
        Gravity = other.Gravity;
      }
      if (other.JumpForce != 0) {
        JumpForce = other.JumpForce;
      }
      if (other.MovementSpeed != 0) {
        MovementSpeed = other.MovementSpeed;
      }
      if (other.RunningSpeedMultiplier != 0) {
        RunningSpeedMultiplier = other.RunningSpeedMultiplier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Gravity = input.ReadUInt32();
            break;
          }
          case 16: {
            JumpForce = input.ReadUInt32();
            break;
          }
          case 24: {
            MovementSpeed = input.ReadUInt32();
            break;
          }
          case 32: {
            RunningSpeedMultiplier = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Gravity = input.ReadUInt32();
            break;
          }
          case 16: {
            JumpForce = input.ReadUInt32();
            break;
          }
          case 24: {
            MovementSpeed = input.ReadUInt32();
            break;
          }
          case 32: {
            RunningSpeedMultiplier = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
